# PostgreSQL configuration for Rails
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maino_filmes_development
  username: postgres
  password: 257941
  host: localhost
  port: 5432

test:
  <<: *default
  database: maino_filmes_test
  username: postgres
  password: 257941
  host: localhost
  port: 5432

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

queue:
  <<: *production

cache:
  <<: *production

cable:
  <<: *production
